name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install valgrind
      run: sudo apt-get install valgrind
    
    - name: Setup Git submodules
      run: git submodule update --init --recursive
      
    - name: Compile with debug flags
      run: make debug
      
    - name: Run valgrind
      run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./main main
